import Head from "next/head";
import {
  Container,
  Main,
  Title,
  Description,
  Footer,
  Custom,
} from "../components/tampilan";
import Link from "next/link";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>langgarku.id</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>
          Welcome to <Link href="https://nextjs.org">langgarku.id</Link>
        </Title>
        <Description>Project membuat aplikasi langgarku.id</Description>
        <Custom>Edit</Custom>
      </Main>

      <Footer>
        <p>on progress 🚀</p>
      </Footer>
    </Container>
  );
}
