import Head from "next/head";
import {
  Container,
  Main,
  Title,
  Description,
  Footer,
  Custom,
} from "../components/tampilan";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>langgarku.id</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <div>
          <ul>
            <li>
              <Link href="/about">About</Link>
            </li>
            <li>
              <Link href="/blog">Blog</Link>
            </li>
          </ul>
        </div>
        <Title>
          Welcome to <Link href="https://nextjs.org">langgarku.id</Link>
        </Title>
        <Description>Project membuat aplikasi langgarku.id</Description>
        <Custom>Edit</Custom>
      </Main>
      <Image src="/vercel.svg" width="400" height="400" />
      <Image
        src="https://avatars.githubusercontent.com/u/53314006?v=4"
        width="300"
        height="500"
      />
      <Image
        src="https://pbs.twimg.com/profile_images/1331805142593589249/S00bozLg_400x400.jpg"
        width="500"
        height="500"
      />

      <Footer>
        <p>on progress 🚀</p>
      </Footer>
    </Container>
  );
}
