import Head from "next/head";
import styled from "styled-components";
import Link from "next/link";
// import styles from "../styles/Home.module.css";

const Container = styled.div`
  min-height: 100vh;
  padding: 0 0.5rem;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
`;

const Main = styled.div`
  padding: 5rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const Title = styled.h1`
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
`;

const Description = styled.p`
  line-height: 1.5;
  font-size: 1.5rem;
`;

const Footer = styled.div`
  width: 100%;
  height: 100px;
  border-top: 1px solid #eaeaea;
  display: flex;
  justify-content: center;
  align-items: center;
`;

export default function Home() {
  return (
    <Container>
      <Head>
        <title>langgarku.id</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>
          Welcome to <Link href="https://nextjs.org">langgarku.id</Link>
        </Title>
        <Description>Project membuat aplikasi langgarku.id</Description>
      </Main>

      <Footer>
        <p>on progress 🚀</p>
      </Footer>
    </Container>
  );
}
